language: java
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
branches:
  only:
    - master
before_install:
script:
  - ./gradlew test build
  - pwd
after_success:
  - test $TRAVIS_BRANCH = "master" && rsync -chavzP --rsh="sshpass -p $FTP_PASSWD ssh -o StrictHostKeyChecking=no -l $FTP_USER" build/libs/debty-0.0.1-SNAPSHOT.jar $FTP_USER@3.93.154.97:/home/ubuntu

