language: java
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
branches:
  only:
    - master
before_install:
script:
  - ./gradlew test bootJar
  - pwd
after_success:  
  - sshpass -p '$FTP_PWD' rsync --progress -avz -e ssh $FTP_USER@$FTP_ADDR:/home/ubuntu build/libs/debty-0.0.1-SNAPSHOT.jar/
  # rsync -PazSHAX --rsh "sshpass -p $FTP_PWD ssh -o StrictHostKeyChecking=no" build/libs/debty-0.0.1-SNAPSHOT.jar $FTP_USER@$FTP_ADDR:/home/ubuntu
  # sshpass -p $FTP_PWD ssh -o StrictHostKeyChecking=no $FTP_USER@$FTP_ADDR  'pwd; java -jar debty-0.0.1-SNAPSHOT.jar &' 
