language: java
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
branches:
  only:
    - master
before_install:
script:
  - ./gradlew test bootJar
  - pwd
after_success:  
  - chmod 400 aws.pem
  - rsync -PazSHAX --rsh "ssh -i "aws.pem" -o StrictHostKeyChecking=no" build/libs/debty-0.0.1-SNAPSHOT.jar ubuntu@3.93.154.97:/home/ubuntu
  - ssh -i "aws.pem" -o StrictHostKeyChecking=no -t 'pwd; java -jar debty-0.0.1-SNAPSHOT.jar' ubuntu@3.93.154.97 
