language: java
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
branches:
  only:
    - master
before_install:
script:
  - ./gradlew test build
  - pwd
after_success:
rsync -PazSHAX --rsh "ssh -i aws.pem" --rsync-path "sudo rsync" \
  build/libs/debty-0.0.1-SNAPSHOT.jar ubuntu@ec2-3-93-154-97.compute-1.amazonaws.com:home/ubuntu/
  pwd
