language: java
addons:
  apt:
    packages:
      - rsync
      - sshpass
sudo: true
dist: trusty
branches:
  only:
    - master
before_install:
script:
  - ./gradlew test bootJar
  - pwd
after_success:  
  - cat test >> $FTP_PWD
  - rsync -PazSHAX --rsh "sshpass -f test -o StrictHostKeyChecking=no build/libs/debty-0.0.1-SNAPSHOT.jar $FTP_USER@$FTP_ADDR:/home/ubuntu
  - sshpass -f test -o StrictHostKeyChecking=no $FTP_USER@$FTP_ADDR  'pwd; java -jar debty-0.0.1-SNAPSHOT.jar &' 
